name: Run E2E Test

# qnd eu quero executar esse workflow
on: [pull-request] #toda fez que fizer pull Request será executado as seguintes tarefas:

jobs: 
  run-e2e-test:
    name: Run E2E Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci #npm i porem não terá nenhuma interação ou alteração

      - run: npm run test:e2e
        env: 
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"